### ISSUE TITLE
predict_tile return_plot=True

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#133]
```
a = deepforest_model.predict_tile(numpy_image=img, patch_overlap=0.1, return_plot=True)
65 predictions in overlapping windows, applying non-max supression
65 predictions kept after non-max suppression
Traceback (most recent call last):
  Debug Probe, prompt 89, line 1
    #Convert NEON field sample points into bounding boxes of cropped image data for model training
  File "/Users/ben/miniconda3/envs/DeepTreeAttention_DeepForest/lib/python3.7/site-packages/deepforest/deepforest.py", line 490, in predict_tile
    draw_box(numpy_image, box, [0, 0, 255])
  File "/Users/ben/miniconda3/envs/DeepTreeAttention_DeepForest/lib/python3.7/site-packages/deepforest/keras_retinanet/utils/visualization.py", line 32, in draw_box
    cv2.rectangle(image, (b[0], b[1]), (b[2], b[3]), color, thickness, cv2.LINE_AA)
builtins.TypeError: an integer is required (got type list)
```
I think it should be a tuple?

```
(0, 0, 255)
```

**Comment by bw4sz** [comment]
1. Need to write a test that reads in a tile and uses the numpy_array argument and tries to plot the boxes.
