### ISSUE TITLE
Installation outdated for Windows

### ISSUE THREAD

**Issue by casbolwerk** [weecology/DeepForest#140]
**Describe the bug**
I think the installation is outdated for Windows. When installing, I get multiple errors. Then when I resolved those, it still didn't work due to version dependencies that aren't given. I hope I remember all the problems.

Maybe some extra mention that conda doesn't work for Windows is handy. Also, I couldn't get the source installation to work immediately, but didn't give it a good try.

**To Reproduce**
1. Try to install on Windows
2. Pip install 
3. Error due to matplotlib version 3.3 (has to be downgraded to version 3.2)
4. Error due to keras_retinanet not being installed yet (install from bw4sz and put into deepforest folder)
5. Error due to setup.py not being run yet (run ***python setup.py build_ext --inplace*** from deepforest folder)

**Expected behavior**
I expected pip to install all necessary things, with dependencies taken care of.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 0.2.19(?)

**Additional context**
The pip command was run in a fresh virtualenv, after concluding conda didn't work for windows.

Relevant links:
https://stackoverflow.com/questions/64291087/matplotlib-module-sip-has-no-attribute-setapi/64417064
Fix for the kerinanet issue in FAQ of
https://github.com/fizyr/keras-retinanet#faq

**Comment by casbolwerk** [comment]
To be clear, I fixed the issues and can now run the example prediction succesfully

**Comment by bw4sz** [comment]
Thanks for the issue! I do not believe you have installed correctly. Or atleast there is something specific about your setup? Here is a blank windows azure VM (https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/). What python version do you have? I need to make that part of issue template.

I cannot reproduce.
```
w4sz@windowstest C:\Users\bw4sz>conda create  --name test python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.9.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: c:\Miniconda\envs\test

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.10.14 |                0         122 KB
    certifi-2020.6.20          |           py37_0         156 KB
    openssl-1.1.1h             |       he774522_0         4.8 MB
    pip-20.2.3                 |           py37_0         1.8 MB
    python-3.7.9               |       h60c2a47_0        14.4 MB
    setuptools-50.3.0          |   py37h9490d1a_1         727 KB
    sqlite-3.33.0              |       h2a8f88b_0         809 KB
    vc-14.1                    |       h0510ff6_4           6 KB
    vs2015_runtime-14.16.27012 |       hf0eaf9b_3         1.2 MB
    wheel-0.35.1               |             py_0          37 KB
    wincertstore-0.2           |           py37_0          14 KB
    ------------------------------------------------------------
                                           Total:        24.0 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.10.14-0
  certifi            pkgs/main/win-64::certifi-2020.6.20-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1h-he774522_0
  pip                pkgs/main/win-64::pip-20.2.3-py37_0
  python             pkgs/main/win-64::python-3.7.9-h60c2a47_0
  setuptools         pkgs/main/win-64::setuptools-50.3.0-py37h9490d1a_1
  sqlite             pkgs/main/win-64::sqlite-3.33.0-h2a8f88b_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_3
  wheel              pkgs/main/noarch::wheel-0.35.1-py_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4


Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2020.6.20    | 156 KB    | ######################################################################################################################### | 100%
vc-14.1              | 6 KB      | ######################################################################################################################### | 100%
setuptools-50.3.0    | 727 KB    | ######################################################################################################################### | 100%
sqlite-3.33.0        | 809 KB    | ######################################################################################################################### | 100%
wincertstore-0.2     | 14 KB     | ######################################################################################################################### | 100%
vs2015_runtime-14.16 | 1.2 MB    | ######################################################################################################################### | 100%
openssl-1.1.1h       | 4.8 MB    | ######################################################################################################################### | 100%
ca-certificates-2020 | 122 KB    | ######################################################################################################################### | 100%
python-3.7.9         | 14.4 MB   | ######################################################################################################################### | 100%
wheel-0.35.1         | 37 KB     | ######################################################################################################################### | 100%
pip-20.2.3           | 1.8 MB    | ######################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate


bw4sz@windowstest C:\Users\bw4sz>conda activate test

(test) bw4sz@windowstest C:\Users\bw4sz>pip install DeepForest
Collecting DeepForest
  Downloading deepforest-0.3.2-cp37-cp37m-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 85 kB/s
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
     |████████████████████████████████| 216 kB 3.3 MB/s
Collecting matplotlib
  Downloading matplotlib-3.3.2-cp37-cp37m-win_amd64.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 6.4 MB/s
Collecting tqdm
  Downloading tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 708 kB/s
Collecting keras==2.3.0
  Downloading Keras-2.3.0-py2.py3-none-any.whl (377 kB)
     |████████████████████████████████| 377 kB ...
Collecting opencv-python
  Downloading opencv_python-4.4.0.44-cp37-cp37m-win_amd64.whl (33.5 MB)
     |████████████████████████████████| 33.5 MB 6.4 MB/s
Collecting pandas
  Downloading pandas-1.1.3-cp37-cp37m-win_amd64.whl (8.7 MB)
     |████████████████████████████████| 8.7 MB 6.4 MB/s
Collecting scipy
  Downloading scipy-1.5.3-cp37-cp37m-win_amd64.whl (31.2 MB)
     |████████████████████████████████| 31.2 MB 6.8 MB/s
Collecting keras-resnet==0.1.0
  Downloading keras-resnet-0.1.0.tar.gz (6.8 kB)
Collecting Pillow
  Downloading Pillow-8.0.0-cp37-cp37m-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB ...
Collecting tensorflow==1.14.0
  Downloading tensorflow-1.14.0-cp37-cp37m-win_amd64.whl (68.3 MB)
     |████████████████████████████████| 68.3 MB 36 kB/s
Collecting progressbar2
  Using cached progressbar2-3.53.1-py2.py3-none-any.whl (25 kB)
Collecting slidingwindow
  Downloading slidingwindow-0.0.14-py3-none-any.whl (9.0 kB)
Collecting h5py
  Downloading h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 6.4 MB/s
Collecting xmltodict
  Downloading xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 953 kB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting numpy>=1.15
  Downloading numpy-1.19.2-cp37-cp37m-win_amd64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 60 kB/s
Requirement already satisfied: certifi>=2020.06.20 in c:\miniconda\envs\test\lib\site-packages (from matplotlib->DeepForest) (2020.6.20)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp37-none-win_amd64.whl (57 kB)
     |████████████████████████████████| 57 kB 2.7 MB/s
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB ...
Collecting keras-applications>=1.0.6
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 3.2 MB/s
Collecting keras-preprocessing>=1.0.5
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 253 kB/s
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 6.4 MB/s
Collecting google-pasta>=0.1.6
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 1.2 MB/s
Collecting gast>=0.2.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting absl-py>=0.7.0
  Downloading absl_py-0.10.0-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB ...
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0
  Downloading tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488 kB)
     |████████████████████████████████| 488 kB 6.8 MB/s
Collecting wrapt>=1.11.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting astor>=0.6.0
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting protobuf>=3.6.1
  Downloading protobuf-3.13.0-cp37-cp37m-win_amd64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 6.4 MB/s
Collecting grpcio>=1.8.6
  Downloading grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 6.4 MB/s
Collecting python-utils>=2.3.0
  Downloading python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Collecting psutil
  Downloading psutil-5.7.2-cp37-cp37m-win_amd64.whl (242 kB)
     |████████████████████████████████| 242 kB ...
Requirement already satisfied: setuptools>=41.0.0 in c:\miniconda\envs\test\lib\site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0->DeepForest) (50.3.0.post20201006)
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB ...
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.2-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 1.8 MB/s
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Downloading zipp-3.3.1-py3-none-any.whl (5.3 kB)
Building wheels for collected packages: keras-resnet, wrapt, termcolor
  Building wheel for keras-resnet (setup.py) ... done
  Created wheel for keras-resnet: filename=keras_resnet-0.1.0-py2.py3-none-any.whl size=13349 sha256=9c596acb3429861048496e71b7caffa7ffe96bba214ecbb95da50888b092f196
  Stored in directory: c:\users\bw4sz\appdata\local\pip\cache\wheels\a6\20\57\d7b7be8556e2ebf36345b3df4068a9a13bb90e4a2cc85a6994
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-win_amd64.whl size=33410 sha256=5a9f29688e6ea01f04dacb6b7e79438abdc9e7b089de9a55e5b82f0f50ddbd28
  Stored in directory: c:\users\bw4sz\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=c0b3bb0ca6db82ccb641506f4b6482c24e2ac712103cd930008ba68619481841
  Stored in directory: c:\users\bw4sz\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
Successfully built keras-resnet wrapt termcolor
Installing collected packages: six, pyyaml, pyparsing, cycler, numpy, kiwisolver, Pillow, python-dateutil, matplotlib, tqdm, h5py, keras-applications, scipy, keras-preprocessing, keras, opencv-
python, pytz, pandas, keras-resnet, google-pasta, gast, absl-py, tensorflow-estimator, wrapt, astor, grpcio, protobuf, werkzeug, zipp, importlib-metadata, markdown, tensorboard, termcolor, tens
orflow, python-utils, progressbar2, psutil, slidingwindow, xmltodict, DeepForest
Successfully installed DeepForest-0.3.2 Pillow-8.0.0 absl-py-0.10.0 astor-0.8.1 cycler-0.10.0 gast-0.4.0 google-pasta-0.2.0 grpcio-1.32.0 h5py-2.10.0 importlib-metadata-2.0.0 keras-2.3.0 keras-
applications-1.0.8 keras-preprocessing-1.1.2 keras-resnet-0.1.0 kiwisolver-1.2.0 markdown-3.3.2 matplotlib-3.3.2 numpy-1.19.2 opencv-python-4.4.0.44 pandas-1.1.3 progressbar2-3.53.1 protobuf-3.
13.0 psutil-5.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 python-utils-2.4.0 pytz-2020.1 pyyaml-5.3.1 scipy-1.5.3 six-1.15.0 slidingwindow-0.0.14 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-e
stimator-1.14.0 termcolor-1.1.0 tqdm-4.50.2 werkzeug-1.0.1 wrapt-1.12.1 xmltodict-0.12.0 zipp-3.3.1
```
Loads without error

```
(test) bw4sz@windowstest C:\Users\bw4sz>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Matplotlib is building the font cache; this may take a moment.
Using TensorFlow backend.
>>>
```
Conda build passes on windows, if there is an issue there, it probably belongs: https://github.com/conda-forge/deepforest-feedstock

I'm going to leave this issue open in case others have problems and can document the specific configuration that lead to an error. I can confirm from above that pip install builds on conda python 3.7 env on a blank azure vm. DeepForest is a brand new package, so please leave as many issues as possible to improve docs and usability.

**Comment by casbolwerk** [comment]
For some reason, it's still not working. When following your steps, I get an error when importing deepforest.

```

(base) C:\Users\casbo>conda create --name deepftest python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Users\casbo\anaconda3\envs\deepftest

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-20.2.4                 |           py37_0         1.8 MB
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.10.14-0
  certifi            pkgs/main/win-64::certifi-2020.6.20-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1h-he774522_0
  pip                pkgs/main/win-64::pip-20.2.4-py37_0
  python             pkgs/main/win-64::python-3.7.9-h60c2a47_0
  setuptools         pkgs/main/win-64::setuptools-50.3.0-py37h9490d1a_1
  sqlite             pkgs/main/win-64::sqlite-3.33.0-h2a8f88b_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_3
  wheel              pkgs/main/noarch::wheel-0.35.1-py_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-20.2.4           | 1.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate deepftest
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\casbo>conda activate deepftest

(deepftest) C:\Users\casbo>pip install DeepForest
Collecting DeepForest
  Using cached deepforest-0.3.2-cp37-cp37m-win_amd64.whl (9.2 MB)
Collecting progressbar2
  Using cached progressbar2-3.53.1-py2.py3-none-any.whl (25 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
Collecting tensorflow==1.14.0
  Using cached tensorflow-1.14.0-cp37-cp37m-win_amd64.whl (68.3 MB)
Collecting tqdm
  Using cached tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
Collecting keras-resnet==0.1.0
  Using cached keras-resnet-0.1.0.tar.gz (6.8 kB)
Collecting scipy
  Using cached scipy-1.5.3-cp37-cp37m-win_amd64.whl (31.2 MB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting xmltodict
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting Pillow
  Using cached Pillow-8.0.0-cp37-cp37m-win_amd64.whl (2.1 MB)
Collecting slidingwindow
  Using cached slidingwindow-0.0.14-py3-none-any.whl (9.0 kB)
Collecting opencv-python
  Using cached opencv_python-4.4.0.44-cp37-cp37m-win_amd64.whl (33.5 MB)
Collecting pandas
  Using cached pandas-1.1.3-cp37-cp37m-win_amd64.whl (8.7 MB)
Collecting h5py
  Using cached h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting matplotlib
  Using cached matplotlib-3.3.2-cp37-cp37m-win_amd64.whl (8.5 MB)
Collecting keras==2.3.0
  Using cached Keras-2.3.0-py2.py3-none-any.whl (377 kB)
Collecting python-utils>=2.3.0
  Using cached python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Collecting absl-py>=0.7.0
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
Collecting protobuf>=3.6.1
  Using cached protobuf-3.13.0-cp37-cp37m-win_amd64.whl (1.0 MB)
Collecting gast>=0.2.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting tensorboard<1.15.0,>=1.14.0
  Using cached tensorboard-1.14.0-py3-none-any.whl (3.1 MB)
Collecting astor>=0.6.0
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting numpy<2.0,>=1.14.5
  Using cached numpy-1.19.2-cp37-cp37m-win_amd64.whl (12.9 MB)
Requirement already satisfied: wheel>=0.26 in c:\users\casbo\anaconda3\envs\deepftest\lib\site-packages (from tensorflow==1.14.0->DeepForest) (0.35.1)
Collecting keras-applications>=1.0.6
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting grpcio>=1.8.6
  Using cached grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting keras-preprocessing>=1.0.5
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Processing c:\users\casbo\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2\termcolor-1.1.0-py3-none-any.whl
Processing c:\users\casbo\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6\wrapt-1.12.1-cp37-cp37m-win_amd64.whl
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0
  Using cached tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488 kB)
Collecting google-pasta>=0.1.6
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting psutil
  Using cached psutil-5.7.2-cp37-cp37m-win_amd64.whl (242 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp37-none-win_amd64.whl (57 kB)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\casbo\anaconda3\envs\deepftest\lib\site-packages (from matplotlib->DeepForest) (2020.6.20)
Requirement already satisfied: setuptools in c:\users\casbo\anaconda3\envs\deepftest\lib\site-packages (from protobuf>=3.6.1->tensorflow==1.14.0->DeepForest) (50.3.0.post20201006)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.2-py3-none-any.whl (95 kB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Using cached zipp-3.3.1-py3-none-any.whl (5.3 kB)
Building wheels for collected packages: keras-resnet
  Building wheel for keras-resnet (setup.py) ... done
  Created wheel for keras-resnet: filename=keras_resnet-0.1.0-py2.py3-none-any.whl size=13349 sha256=984b889d29eb627f6e6b51aa7053779b973f87d1532ea0eb83a3d3d272fd972a
  Stored in directory: c:\users\casbo\appdata\local\pip\cache\wheels\a6\20\57\d7b7be8556e2ebf36345b3df4068a9a13bb90e4a2cc85a6994
Successfully built keras-resnet
Installing collected packages: six, python-utils, progressbar2, pyyaml, absl-py, protobuf, gast, werkzeug, numpy, grpcio, zipp, importlib-metadata, markdown, tensorboard, astor, h5py, keras-applications, keras-preprocessing, termcolor, wrapt, tensorflow-estimator, google-pasta, tensorflow, tqdm, scipy, keras, keras-resnet, xmltodict, Pillow, psutil, slidingwindow, opencv-python, python-dateutil, pytz, pandas, cycler, pyparsing, kiwisolver, matplotlib, DeepForest
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

slim 0.1 requires tf-slim>=1.1, which is not installed.
Successfully installed DeepForest-0.3.2 Pillow-8.0.0 absl-py-0.10.0 astor-0.8.1 cycler-0.10.0 gast-0.4.0 google-pasta-0.2.0 grpcio-1.32.0 h5py-2.10.0 importlib-metadata-2.0.0 keras-2.3.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 keras-resnet-0.1.0 kiwisolver-1.2.0 markdown-3.3.2 matplotlib-3.3.2 numpy-1.19.2 opencv-python-4.4.0.44 pandas-1.1.3 progressbar2-3.53.1 protobuf-3.13.0 psutil-5.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 python-utils-2.4.0 pytz-2020.1 pyyaml-5.3.1 scipy-1.5.3 six-1.15.0 slidingwindow-0.0.14 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 termcolor-1.1.0 tqdm-4.50.2 werkzeug-1.0.1 wrapt-1.12.1 xmltodict-0.12.0 zipp-3.3.1

(deepftest) C:\Users\casbo>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\deepforest\deepforest.py", line 20, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\casbo\anaconda3\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\qt_compat.py", line 170, in <module>
    _setup()
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\qt_compat.py", line 130, in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
  File "C:\Users\casbo\anaconda3\envs\deepftest\lib\site-packages\matplotlib\backends\qt_compat.py", line 113, in _setup_pyqt4_internal
    sip.setapi(_sip_api, api)
AttributeError: module 'sip' has no attribute `'setapi'`
```

It is installing a cached version of DeepForest, maybe that's a problem. When I downgrade matplotlib, it's working.

```
(deepftest) C:\Users\casbo>conda install matplotlib=3.2
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Users\casbo\anaconda3\envs\deepftest

  added / updated specs:
    - matplotlib=3.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freetype-2.10.4            |       hd328e21_0         466 KB
    mkl_fft-1.2.0              |   py37h45dec08_0         118 KB
    ------------------------------------------------------------
                                           Total:         585 KB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  cycler             pkgs/main/win-64::cycler-0.10.0-py37_0
  freetype           pkgs/main/win-64::freetype-2.10.4-hd328e21_0
  icu                pkgs/main/win-64::icu-58.2-ha925a31_3
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.2-254
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  kiwisolver         pkgs/main/win-64::kiwisolver-1.2.0-py37h74a9793_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  matplotlib         pkgs/main/win-64::matplotlib-3.2.2-0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.2.2-py37h64f37c6_0
  mkl                pkgs/main/win-64::mkl-2020.2-256
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.2.0-py37h45dec08_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.1-py37h47e9c7a_0
  numpy              pkgs/main/win-64::numpy-1.19.1-py37h5510c5b_0
  numpy-base         pkgs/main/win-64::numpy-base-1.19.1-py37ha3acd2a_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.7-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  six                pkgs/main/noarch::six-1.15.0-py_0
  tornado            pkgs/main/win-64::tornado-6.0.4-py37he774522_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
freetype-2.10.4      | 466 KB    | ############################################################################ | 100%
mkl_fft-1.2.0        | 118 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(deepftest) C:\Users\casbo>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Using TensorFlow backend.
>>>
```

**Comment by bw4sz** [comment]
Thanks for following up, I'm almost certain that matplotlib issue is specific to your environment, it has to do with the QT backend. This kind of thing (generally) https://stackoverflow.com/questions/50222011/importing-matplotlib-pyplot-fails-in-pycharm-due-to-attributeerror-module-pyqt. I'm glad you have a working install. I'm going to close because I don't think there is any universal I can do here. let me know if you run into other problems.
