### ISSUE TITLE
OSError: Unable to create file (unable to open file: name = 'snapshot\final_model.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

### ISSUE THREAD

**Issue by twinsben94** [weecology/DeepForest#154]
**Describe the bug**
Hello, I am a university student(master course) in South Korea, and I'm so interested in your DeepForest paper and code. However, when I open your code and run them, I had some issue. 

**To Reproduce**

1) This is my code.

from deepforest import deepforest
from deepforest import get_data

test_model = deepforest.deepforest()

test_model.config["epochs"] = 1
test_model.config["save-snapshot"] = False
test_model.config["steps"] = 1

annotations_file = get_data("testfile_deepforest.csv")

test_model.train(annotations=annotations_file, input_type="fit_generator")

test_model.model.save("snapshot\\final_model.h5")

print("Practice(3) Successful!")

2) And this is terminal..

Epoch 1/1
1/1 [==============================] - 21s 21s/step - loss: 3.9762 - regression_loss: 2.8483 - classification_loss: 1.1279
Traceback (most recent call last):
  File "c:/ProgramData/Anaconda3/envs/venv_deepforest/practice_deepforest/practice)0107(3).py", line 17, in <module>
    test_model.model.save("snapshot\\final_model.h5")
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\keras\engine\network.py", line 1152, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\keras\engine\saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\keras\engine\saving.py", line 540, in save_model
    with H5Dict(filepath, mode='w') as h5dict:
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\keras\utils\io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'snapshot\final_model.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

**Expected behavior**
I don't know why "OSError" comes out.. I guessed that "Is it because I didn't make a training data?", but I'm not sure. So I want to listen your comments.. In fact I'm a baby of Python(I usually use MATLAB, but after I read your paper, DeepForest made me to start Python haha.. I really want to test your code and see the result myself)

**Screenshots**
![image](https://user-images.githubusercontent.com/76718413/103852289-ecc98380-50ee-11eb-855d-197caec5255e.png)

this is my terminal, and..
![image](https://user-images.githubusercontent.com/76718413/103852329-feab2680-50ee-11eb-9ecd-cce50a3009ea.png)

this is my code(I just copied yours and run them :) )

**Desktop (please complete the following information):**
 - OS: Windows 10, 64bit, Intel(r) Core(TM) i7-6500U CPU @ 2.50GHz
 - Browser chrome

**Additional context**
This is my conda list... :) 

absl-py                   0.11.0                   pypi_0    pypi
alabaster                 0.7.12                   py37_0
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py37_0
astor                     0.8.1                    pypi_0    pypi
astroid                   2.4.2                    py37_0
async_generator           1.10             py37h28b3542_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.4                      py_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bcrypt                    3.2.0            py37he774522_0
black                     19.10b0                    py_0
bleach                    3.2.1                      py_0
brotlipy                  0.7.0           py37h2bbff1b_1003
ca-certificates           2020.12.8            haa95532_0
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.4           py37hcd4344a_0
chardet                   4.0.0           py37haa95532_1003
click                     7.1.2                      py_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.3.1            py37hcd4344a_0
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                      py_0
deepforest                0.3.5                    pypi_0    pypi
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
flake8                    3.8.4                      py_0
future                    0.18.2                   py37_1
gast                      0.4.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        3.3.0                    pypi_0    pypi
importlib_metadata        2.0.0                         1
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.19.0           py37hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.6.4                      py_0
jedi                      0.17.2           py37haa95532_1
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.0            py37haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keras                     2.3.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keras-resnet              0.1.0                    pypi_0    pypi
keyring                   21.8.0           py37haa95532_0
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.4.3            py37h2bbff1b_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.3.3                    pypi_0    pypi
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37hfa6e2cd_1001
mypy_extensions           0.4.3                    py37_0
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nest-asyncio              1.4.3              pyhd3eb1b0_0
numpy                     1.19.5                   pypi_0    pypi
numpydoc                  1.1.0              pyhd3eb1b0_1
opencv-python             4.5.1.48                 pypi_0    pypi
openssl                   1.1.1i               h2bbff1b_0
packaging                 20.8               pyhd3eb1b0_0
pandas                    1.2.0                    pypi_0    pypi
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py37haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathspec                  0.7.0                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.0                    pypi_0    pypi
pip                       20.3.3           py37haa95532_0
pluggy                    0.13.1                   py37_0
progressbar2              3.53.1                   pypi_0    pypi
prompt-toolkit            3.0.8                      py_0
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.7.3              pyhd3eb1b0_0
pylint                    2.6.0                    py37_0
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.0              pyhd3eb1b0_0
pynacl                    1.4.0            py37h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.17.3           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-utils              2.4.0                    pypi_0    pypi
pytz                      2020.5             pyhd3eb1b0_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1001
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0           py37hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.1                      py_0
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.11.13       py37h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
rope                      0.18.0                     py_0
rtree                     0.9.4            py37h21ff451_1
scipy                     1.6.0                    pypi_0    pypi
setuptools                51.0.0           py37haa95532_2
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
slidingwindow             0.0.14                   pypi_0    pypi
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
sphinx                    3.4.2              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.2.0            py37haa95532_0
spyder-kernels            1.10.1           py37haa95532_0
sqlite                    3.33.0               h2a8f88b_0
tensorboard               1.14.0                   pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
testpath                  0.4.4                      py_0
three-merge               0.1.1              pyhd3eb1b0_0
toml                      0.10.1                     py_0
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.55.1                   pypi_0    pypi
traitlets                 5.0.5                      py_0
typed-ast                 1.4.1            py37he774522_0
typing_extensions         3.7.4.3                    py_0
ujson                     4.0.1            py37ha925a31_0
urllib3                   1.26.2             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  0.10.4           py37haa95532_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4

Lots of Thanks for amazing code!

**Comment by twinsben94** [comment]
Oh my god,,, I solved this problem. Just a trivial path issue haha.. Thank you :)
