### ISSUE TITLE
ValueError: No image names match between the file

### ISSUE THREAD

**Issue by landkwon94** [weecology/DeepForest#157]
Hello again, may I ask some issue again? :) 

I'm just following these sample codes by myself now. 
https://deepforest.readthedocs.io/en/latest/case_study_FrenchGuiana.html

When I first use these codes, it works!

But I changed some arguments' name to use these codes for other purpose. I didn't changed my directory, I just made some new directory folder and changed my codes related to them,,, But it makes some errors.

I guess it is hard to show you my directory folder address and my sample code, so I attached all of those information. If you have time, please help me haha ...

1) This code is my original Code (Which didn't have any problem)
To make model and weights which were trained by several photos, I made for loop. That is the only difference with your code I think..

------------------------------------------------------------------------------------------------------------------------------------

![1](https://user-images.githubusercontent.com/73383617/106378397-c80fb580-63e7-11eb-9e6d-011e434f4db8.png)

#######The number of photos were 30, so I made 30 XML annotation files.... And finally, I made 30 csv files from them. ##########

#######Because my jpg file names are for example, "small01.jpg, small02.jpg, etc. I made a list to make a for loop. ##########

![2](https://user-images.githubusercontent.com/73383617/106378404-dbbb1c00-63e7-11eb-8d2c-0b12354e924a.png)

#######I know, you used 'get_data' function, but in the case of drone-case study, they used a full address to get the image file. So I followed them and it works! ##########

![3](https://user-images.githubusercontent.com/73383617/106378513-e1fdc800-63e8-11eb-9d04-1a7de808a1b9.png)

------------------------------------------------------------------------------------------------------------------------------------

And this is the similar code I made. But very strangely, this doesn't work.... It show this error. 

------------------------------------------------------------------------------------------------------------------------------------

ValueError: No image names match between the file:middle_train_annotation_01.csv and the image_path: middle01.jpg. Reminder that image paths should be the relative path (e.g. 'image_name.tif'), not the full path (e.g. path/to/dir/image_name.tif)

------------------------------------------------------------------------------------------------------------------------------------

I was so curious, because I only changed my file name and some directory.... this is my second code.

------------------------------------------------------------------------------------------------------------------------------------

![1](https://user-images.githubusercontent.com/73383617/106378524-f5a92e80-63e8-11eb-8891-ccf588b03dde.png)

#####In this case, I only have 3 photos, so the number is range(1,4) #####

![2](https://user-images.githubusercontent.com/73383617/106378529-035eb400-63e9-11eb-898f-78bc5f4b5ad9.png)

![3](https://user-images.githubusercontent.com/73383617/106378532-0659a480-63e9-11eb-9317-50edc94f90be.png)

------------------------------------------------------------------------------------------------------------------------------------

So I tried other method.

1) Move my jpg files and csv annotation files to  \Lib\site-packages\deepforest\data  and I tried 'get_data'
2) Move my jpg files and csv annotation files to  crop_dir = os.getcwd()
3) make them same name.

But any solution doesn't work for me...

------------------------------------------------------------------------------------------------------------------------------------

I guess you are confusing about my folder and directory, so let me show you them..

1) This is my folder (1)

![image](https://user-images.githubusercontent.com/73383617/106378100-3d2dbb80-63e5-11eb-9ecd-2c47826201db.png)

my code is "Training_Code.py" and my image is middle01 ~ 03.jpg, also my annotation file is middle_train_annotation_01 ~ 03.csv

2) Same annotation files are saved in this directory.

![image](https://user-images.githubusercontent.com/73383617/106378137-83831a80-63e5-11eb-8423-7d581e9a41b6.png)

3) Also, same images are saved in this directory.

![image](https://user-images.githubusercontent.com/73383617/106378152-9bf33500-63e5-11eb-931e-d341142a5a20.png)

4) And this is  \Lib\site-packages\deepforest\data directory.

![image](https://user-images.githubusercontent.com/73383617/106378170-cf35c400-63e5-11eb-84e3-c2489a80ef17.png)

------------------------------------------------------------------------------------------------------------------------------------

The error occured in this section... 

 train_annotations = preprocess.split_raster(path_to_raster = Suwon_crop_train,
                                 annotations_file = "middle_train_annotation_" + str(idx+1).zfill(2) + ".csv",
                                 base_dir = crop_dir,
                                 patch_size = 400,
                                 patch_overlap = 0.05)

Traceback (most recent call last):
  File "c:/ProgramData/Anaconda3/envs/venv_deepforest_workspace/workspace(2)_deepforest/eeeee.py", line 49, in <module>
    patch_overlap = 0.05)
  File "C:\ProgramData\Anaconda3\envs\venv_deepforest_workspace\lib\site-packages\deepforest\preprocess.py", line 196, in split_raster
    "(e.g. path/to/dir/image_name.tif)".format(annotations_file, image_name))
ValueError: No image names match between the file:middle_train_annotation_01.csv and the image_path: middle01.jpg. Reminder that image paths should be the relative path (e.g. 'image_name.tif'), not the full path (e.g. path/to/dir/image_name.tif)

------------------------------------------------------------------------------------------------------------------------------------

I think I wrote too much things.. So I guess you will need much time to read all of them. I'm really OK although you reply late. I just want to solve this problem. Please give me a help whenever you have time to deal with it :)

Again, thank you for your nice code!!

**Comment by landkwon94** [comment]
Oh I checked my XML file and I found that file name in the XML file is different with image file haha.. Sorry, I have to study more... Thank you!!!
