### ISSUE TITLE
from deepforest import main failed

### ISSUE THREAD

**Issue by SimonSongg** [weecology/DeepForest#199]
Hello, I am trying to import main. But it failed with following messages.
from deepforest import main
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\deepforest\main.py", line 12, in <module>
    from deepforest import utilities
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\deepforest\utilities.py", line 7, in <module>
    import geopandas as gpd
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\geopandas\_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "D:\anaconda\envs\tree\lib\site-packages\geopandas\_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\geopandas\_compat.py", line 10, in <module>
    import shapely.geos
  File "C:\Users\sf995\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\203.7148.72\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\anaconda\envs\tree\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "D:\anaconda\envs\tree\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] the specified module could not be found.

I am using windows 10 and I should have installed all the required packages. Thanks in advance.

**Comment by bw4sz** [comment]
thanks for the issue, fyi, wrapping code in ```

```
this is code
```
makes it more readable.

Can you confirm when and how you installed. There have been a couple changes. Starting in a clean conda env, please pip install deepforest and show the full run.

**Comment by bw4sz** [comment]
closing for lack of response. Feel free to re-open.
