### ISSUE TITLE
fiona has some errors

### ISSUE THREAD

**Issue by gislain22** [weecology/DeepForest#219]
**Describe the bug**
```python
C:\Users\UTPO0969\.conda\envs\DeepForest\python.exe D:/GitHub/DeepForest/sample_test.py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
Exception ignored in: 'fiona._env.log_error'
Traceback (most recent call last):
  File "C:\Users\UTPO0969\.conda\envs\DeepForest\lib\site-packages\fiona\env.py", line 289, in defenv
    local._env.start()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
Exception ignored in: 'fiona._env.log_error'
Traceback (most recent call last):
  File "C:\Users\UTPO0969\.conda\envs\DeepForest\lib\site-packages\fiona\env.py", line 289, in defenv
    local._env.start()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
Exception ignored in: 'fiona._env.log_error'
Traceback (most recent call last):
  File "C:\Users\UTPO0969\.conda\envs\DeepForest\lib\site-packages\fiona\env.py", line 289, in defenv
    local._env.start()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
Exception ignored in: 'fiona._env.log_error'
Traceback (most recent call last):
  File "C:\Users\UTPO0969\.conda\envs\DeepForest\lib\site-packages\fiona\env.py", line 289, in defenv
    local._env.start()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
Reading config file: deepforest_config.yml
C:\Users\UTPO0969\.conda\envs\DeepForest\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/1.0.0 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/1.0.0

Process finished with exit code 0
```

**To Reproduce**

**Environment (please complete the following information):**
 - OS: windows 10
 - Python version and environment : conda 3.8

**Screenshots**

**Additional context**
my system is setup in french

**Comment by bw4sz** [comment]
This is upstream of this repo. Please make an issue with fiona if you have a fiona issue. Just guessing this literally a french accent mark problem. Try removing all non-standard UTF characters. I think its worth creating an issue,

https://github.com/Toblerity/Fiona/issues/191

since have a global user base is important. Similar issue reported in chinese characters. Just guessing. ONce you have a fiona installation, you can install deepforest on top of it.
