### ISSUE TITLE
Cannot create the given Conda environment.

### ISSUE THREAD

**Issue by yundumbledore** [weecology/DeepForest#3]
Hello, 

I'm just following the guide to redo the process. But I'm stuck at the very beginning phase.

I got error when using the environment requirement file to create a new Conda environment. I'm not sure whether it is caused by your given file or my computer since I've browsed some open and closed issue related to this problem. I'm using a Mac version 10.14.2. The error is as below:

dyn-118-138-95-14:DeepForest-master areoengine$ conda env create -name DeepForest -f=environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 79, in execute
        directory=os.getcwd())
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 84, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 72, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 194, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 106, in compose_node
        if self.parser.check_event(AliasEvent):
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 144, in check_event
        self.current_event = self.state()
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 577, in parse_block_mapping_value
        if self.scanner.check_token(ValueToken):
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 159, in check_token
        while self.need_more_tokens():
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 196, in need_more_tokens
        self.stale_possible_simple_keys()
      File "/Users/areoengine/anaconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 345, in stale_possible_simple_keys
        "could not find expected ':'", self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning a simple key
      in "<unicode string>", line 4, column 1:
        absl-py=0.2.1=py36_0
        ^ (line: 4)
    could not find expected ':'
      in "<unicode string>", line 5, column 1:
        affine=2.2.0=py36_0
        ^ (line: 5)

`$ /Users/areoengine/anaconda3/bin/conda-env create -name DeepForest -f=environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/Users/areoengine/anaconda3
                     PATH=/Library/Frameworks/GDAL.framework/Programs:/Users/areoengine/anaconda
                          3/bin:/Users/areoengine/mongodb/bin:/Users/areoengine/anaconda3/bin:/L
                          ibrary/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/us
                          r/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet
                          :~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/C
                          ommands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamar
                          in Workbooks.app/Contents/SharedSupport/path-bin
          PKG_CONFIG_PATH=/usr/local/opt/protobuf@3.1/lib/pkgconfig
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/areoengine/.condarc
 populated config files : /Users/areoengine/.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /Users/areoengine/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/areoengine/anaconda3/pkgs
                          /Users/areoengine/.conda/pkgs
       envs directories : /Users/areoengine/anaconda3/envs
                          /Users/areoengine/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 

Could you help me out? Thanks very much beforehand. 

Yours sincerely,
Rowen

**Comment by ethanwhite** [comment]
Looks like a typo had crept into `environment.yml`. I just submitted PR to fix it (#4). You can either wait until @bw4sz merges this in (probably later today) and then update or for now you can manually remove the `i` before the `#` on the first line of `environment.yml`.

**Comment by ethanwhite** [comment]
Thanks for reporting!
