### ISSUE TITLE
Error 'preload_images' when training model

### ISSUE THREAD

**Issue by JoelMet** [weecology/DeepForest#310]
Hi,
I saw a similar issue a while ago and hoped that you might have posted a solution. But now the issue ist gone and I cant find any information of how you fixed it.

I have an error message when I try to train a model using DeepForest and the Google Colab environment. I used the same code as shown in your google colab tutorial.

Before I started my code I updated the deepforest package:

```
#install the package, on colab make sure to upgrade existing packages. This is not needed in a clean env.
! pip install --upgrade deepforest albumentations pyyaml

import rasterio
import matplotlib.pyplot as plt
from deepforest import main 
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess
import pandas as pd

# load annotation file
annotations_file = pd.read_csv("annotation_buffer_baumkr_0.6_df.csv")

r = "dop20rgbi_32563_5936_1_hh_2019.tif"
raster = rasterio.open(r)
image_path = os.path.dirname(r)

#Write converted dataframe to file. Saved alongside the images
annotations_file.to_csv(os.path.join(image_path, "train_example.csv"), index=False)

#Find annotation path
annotation_path = os.path.join(image_path, "train_example.csv")
#crop images will save in a newly created directory
#os.mkdir(os.getcwd(),'train_data_folder')
crop_dir = os.path.join(os.getcwd(),'train_data_folder')

train_annotations = preprocess.split_raster(path_to_raster = r,
                                 annotations_file = annotation_path,
                                 base_dir = crop_dir,
                                 patch_size = 500,
                                 patch_overlap = 0.05)

#Split image crops into training and test. Normally these would be different tiles! Just as an example.
image_paths = train_annotations.image_path.unique()

#split 25% validation annotation
valid_paths = np.random.choice(image_paths, int(len(image_paths)*0.25) )
valid_annotations = train_annotations.loc[train_annotations.image_path.isin(valid_paths)]
train_annotations = train_annotations.loc[~train_annotations.image_path.isin(valid_paths)]

#View output
train_annotations.head()
print("There are {} training crown annotations".format(train_annotations.shape[0]))
print("There are {} test crown annotations".format(valid_annotations.shape[0]))

#save to file and create the file dir
annotations_file= os.path.join(crop_dir,"train.csv")
validation_file= os.path.join(crop_dir,"valid.csv")
#Write window annotations file without a header row, same location as the "base_dir" above.
train_annotations.to_csv(annotations_file,index=False)
valid_annotations.to_csv(validation_file,index=False)

#initial the model and change the corresponding config file
m = main.deepforest()
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
#Since this is a demo example and we aren't training for long, only show the higher quality boxes
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training 
m.create_trainer()
#load the lastest release model 
m.use_release()

start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on CPU: {(time.time() - start_time):.2f} seconds ---")
```

Error message:

```
| Name  | Type      | Params
------------------------------------
0 | model | RetinaNet | 32.1 M
------------------------------------
31.9 M    Trainable params
222 K     Non-trainable params
32.1 M    Total params
128.592   Total estimated model params size (MB)

Validation sanity check:
0/? [00:00<?, ?it/s]

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-42-0501e4367b85>](https://localhost:8080/#) in <module>()
      1 start_time = time.time()
      2 
----> 3 m.trainer.fit(m)
      4 
      5 print(f"--- Training on CPU: {(time.time() - start_time):.2f} seconds ---")

16 frames

[/usr/local/lib/python3.7/dist-packages/deepforest/main.py](https://localhost:8080/#) in load_dataset(self, csv_file, root_dir, augment, shuffle, batch_size, train)
    167                                  transforms=self.transforms(augment=augment),
    168                                  label_dict=self.label_dict,
--> 169                                  preload_images=self.config["train"]["preload_images"])
    170 
    171         data_loader = torch.utils.data.DataLoader(

KeyError: 'preload_images'

```

`m.get_transform`

```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-43-184728f657c9>](https://localhost:8080/#) in <module>()
----> 1 m.get_transform

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1176                 return modules[name]
   1177         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1178             type(self).__name__, name))
   1179 
   1180     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'deepforest' object has no attribute 'get_transform'
```

Can you please tell hwo I can fix the error?

**Comment by bw4sz** [comment]
Hi, just for others, can you wrap code into 

```
blocks of code.
```

so it formats. I'll fix the co-lab tutorial, i'll need to re-trigger a python build.

**Comment by JoelMet** [comment]
Sorry my bad. Thanks for your help.

**Comment by Kikihqq** [comment]
I also get the error when i train on my own server:
KeyError: 'preload_images'
How can i fix this?

**Comment by bw4sz** [comment]
I need a user to provide significantly more detail. When did you install, how did you install, what version do you have. I cannot replicate this issue locally and need to understand the conditions when it occurs. Can you confirm whether 

```
pip install deepforest --upgrade
```
solves the issue?

**Comment by Kikihqq** [comment]
I installed it yesterday by  
`conda install deepforest albumentations -c conda-forge`,
The version is `deepforest-1.2.0`
And i run the code :
```
#load the modules
import os
import time
import numpy as np
from deepforest import main 
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess

#convert hand annotations from xml into retinanet format
#The get_data function is only needed when fetching sample package data
YELL_xml = get_data("2019_YELL_2_528000_4978000_image_crop2.xml")
annotation = utilities.xml_to_annotations(YELL_xml)
annotation.head()

#load the image file corresponding to the annotaion file
YELL_train = get_data("2019_YELL_2_528000_4978000_image_crop2.png")
image_path = os.path.dirname(YELL_train)
#Write converted dataframe to file. Saved alongside the images
annotation.to_csv(os.path.join(image_path,"train_example.csv"), index=False)

# 准备训练及和验证集

#Find annotation path
annotation_path = os.path.join(image_path,"train_example.csv")
#crop images will save in a newly created directory
#os.mkdir(os.getcwd(),'train_data_folder')
crop_dir = os.path.join(os.getcwd(),'train_data_folder')
train_annotations= preprocess.split_raster(path_to_raster=YELL_train,
                                 annotations_file=annotation_path,
                                 base_dir=crop_dir,
                                 patch_size=400,
                                 patch_overlap=0.05)

#Split image crops into training and test. Normally these would be different tiles! Just as an example.
image_paths = train_annotations.image_path.unique()
#split 25% validation annotation
valid_paths = np.random.choice(image_paths, int(len(image_paths)*0.25) )
valid_annotations = train_annotations.loc[train_annotations.image_path.isin(valid_paths)]
train_annotations = train_annotations.loc[~train_annotations.image_path.isin(valid_paths)]

#View output
train_annotations.head()
print("There are {} training crown annotations".format(train_annotations.shape[0]))
print("There are {} test crown annotations".format(valid_annotations.shape[0]))

#save to file and create the file dir
annotations_file= os.path.join(crop_dir,"train.csv")
validation_file= os.path.join(crop_dir,"valid.csv")
#Write window annotations file without a header row, same location as the "base_dir" above.
train_annotations.to_csv(annotations_file,index=False)
valid_annotations.to_csv(validation_file,index=False)

# print(annotations_file)

#initial the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training 
m.create_trainer()
#load the lastest release model 
m.use_release()

print("data ok")

start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds ---")

m.get_transform

#save the prediction result to a prediction folder
save_dir = os.path.join(os.getcwd(),'pred_result')
try:
  os.mkdir(save_dir)
except FileExistsError:
  pass
results = m.evaluate(annotations_file, os.path.dirname(annotations_file), iou_threshold = 0.4, savedir= save_dir)
```
And there are some errors:
```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type      | Params
------------------------------------
0 | model | RetinaNet | 32.1 M
------------------------------------
31.9 M    Trainable params
222 K     Non-trainable params
32.1 M    Total params
128.592   Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/pikapikaq/Desktop/TreeHeight/DeepTree/test2.py", line 73, in <module>
    m.trainer.fit(m)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1371, in _run_sanity_check
    self._evaluation_loop._reload_evaluation_dataloaders()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 170, in _reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 551, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 456, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(mode, model=model)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 611, in request_dataloader
    dataloader = source.dataloader()
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 296, in dataloader
    return self.instance.trainer.call_hook(self.name, pl_module=self.instance)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
    output = model_fx(*args, **kwargs)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/main.py", line 203, in val_dataloader
    loader = self.load_dataset(csv_file=self.config["validation"]["csv_file"],
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/main.py", line 169, in load_dataset
    preload_images=self.config["train"]["preload_images"])
KeyError: 'preload_images'
```

**Comment by Kikihqq** [comment]
Do i  need try `conda update deepforest` or `pip install deepforest --upgrade` ?

**Comment by ethanwhite** [comment]
1.2.1 has been on conda-forge for a while now, so I'm going to go ahead and close this. If anyone is still having issues please feel free to reopen.
