### ISSUE TITLE
Predict a single image

### ISSUE THREAD

**Issue by Kikihqq** [weecology/DeepForest#312]
I use the guide in `readme.md` to predict a single image
```
csv_file = '/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/data/OSBS_029.tif'
df = m.predict_file(csv_file, root_dir = os.path.dirname(csv_file))
```
But the errors occurred:
```
Traceback (most recent call last):
  File "/home/pikapikaq/Desktop/TreeHeight/DeepTree/test2.py", line 102, in <module>
    df = m.predict_file(csv_file, root_dir = os.path.dirname(csv_file))
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/main.py", line 281, in predict_file
    result = predict.predict_file(model=self.model,
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/predict.py", line 85, in predict_file
    df = pd.read_csv(csv_file)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1231, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 544, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 633, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 18: invalid start byte
```
I think it should be 
```
df= m.predict_image(image=img)
```
But i couldn't get the right answer, when i print `df`,the output is `None`.

How exactly should I predict a single image?  Thans a lot.

The complete code is as follows：
```
#load the modules
import os
import time
import cv2
import numpy as np
from deepforest import main 
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess

#convert hand annotations from xml into retinanet format
#The get_data function is only needed when fetching sample package data
YELL_xml = get_data("2019_YELL_2_528000_4978000_image_crop2.xml")
annotation = utilities.xml_to_annotations(YELL_xml)
annotation.head()

#load the image file corresponding to the annotaion file
YELL_train = get_data("2019_YELL_2_528000_4978000_image_crop2.png")
image_path = os.path.dirname(YELL_train)
#Write converted dataframe to file. Saved alongside the images
annotation.to_csv(os.path.join(image_path,"train_example.csv"), index=False)

# 准备训练及和验证集

#Find annotation path
annotation_path = os.path.join(image_path,"train_example.csv")
#crop images will save in a newly created directory
#os.mkdir(os.getcwd(),'train_data_folder')
crop_dir = os.path.join(os.getcwd(),'train_data_folder')
train_annotations= preprocess.split_raster(path_to_raster=YELL_train,
                                 annotations_file=annotation_path,
                                 base_dir=crop_dir,
                                 patch_size=400,
                                 patch_overlap=0.05)

#Split image crops into training and test. Normally these would be different tiles! Just as an example.
image_paths = train_annotations.image_path.unique()
#split 25% validation annotation
valid_paths = np.random.choice(image_paths, int(len(image_paths)*0.25) )
valid_annotations = train_annotations.loc[train_annotations.image_path.isin(valid_paths)]
train_annotations = train_annotations.loc[~train_annotations.image_path.isin(valid_paths)]

#View output
train_annotations.head()
print("There are {} training crown annotations".format(train_annotations.shape[0]))
print("There are {} test crown annotations".format(valid_annotations.shape[0]))

#save to file and create the file dir
annotations_file= os.path.join(crop_dir,"train.csv")
validation_file= os.path.join(crop_dir,"valid.csv")
#Write window annotations file without a header row, same location as the "base_dir" above.
train_annotations.to_csv(annotations_file,index=False)
valid_annotations.to_csv(validation_file,index=False)

# print(annotations_file)

#initial the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training 
m.create_trainer()
#load the lastest release model 
m.use_release()

print("data ok")

start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds ---")

print()
print(annotations_file)
print()

# annotations_file='/home/pikapikaq/Desktop/TreeHeight/test/1.png'
# annotations_file='/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/data/OSBS_029.csv'

# save the prediction result to a prediction folder
save_dir = os.path.join(os.getcwd(),'pred_result')
try:
  os.mkdir(save_dir)
except FileExistsError:
  pass
results = m.evaluate(annotations_file, os.path.dirname(annotations_file),iou_threshold = 0.4, savedir= save_dir)

# csv_file = '/home/pikapikaq/Desktop/TreeHeight/DeepTree/train_data_folder/2019_YELL_2_528000_4978000_image_crop2_5.png'#'/home/pikapikaq/Desktop/TreeHeight/DeepTree/data/1.jpeg' #'/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/data/OSBS_029.tif'
# img=cv2.imread(csv_file)
# img = img.astype(np.float32)/255
# #print(image.dtype)
# # print(img)
# df = m.predict_image(image=img,return_plot=True)#root_dir = os.path.dirname(csv_file))
# print(df)

csv_file = '/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/data/OSBS_029.tif'
df = m.predict_file(csv_file, root_dir = os.path.dirname(csv_file))
```

**Comment by Kikihqq** [comment]
When i change this 
```
csv_file = '/home/pikapikaq/anaconda3/envs/workspace/lib/python3.9/site-packages/deepforest/data/OSBS_029.csv'
df = m.predict_file(csv_file, root_dir = os.path.dirname(csv_file))
```
It seems to be predict successfully ?
```
          xmin        ymin        xmax        ymax label     score    image_path
0   174.570068    0.000000  228.328796   32.105286  Tree  0.820426  OSBS_029.tif
1   214.701843  206.938736  246.710236  242.256577  Tree  0.803173  OSBS_029.tif
2   331.139771  344.707825  373.449280  388.523010  Tree  0.788395  OSBS_029.tif
3    49.667542   71.701920   83.310760  107.350693  Tree  0.751000  OSBS_029.tif
4   260.880859  239.254517  296.461609  276.904175  Tree  0.744531  OSBS_029.tif
5   325.198700   45.341942  361.886566   82.761589  Tree  0.732352  OSBS_029.tif
6   248.501678   51.102257  277.213104   81.689674  Tree  0.722748  OSBS_029.tif
7   257.570496  198.730591  291.101318  230.857971  Tree  0.698840  OSBS_029.tif
8   272.067688  332.139954  304.205017  367.277832  Tree  0.676571  OSBS_029.tif
9   317.771942  182.516876  345.477692  210.052277  Tree  0.671376  OSBS_029.tif
10   58.106537  298.124756   98.440552  337.296204  Tree  0.669235  OSBS_029.tif
11   98.653511  308.250031  151.967651  363.851410  Tree  0.662281  OSBS_029.tif
12  276.633911    1.493249  309.077515   31.345825  Tree  0.658915  OSBS_029.tif
13   18.240349  346.859467   57.535637  386.918243  Tree  0.656180  OSBS_029.tif
14  197.837311  339.082123  229.021881  370.755585  Tree  0.642837  OSBS_029.tif
15  291.689850  372.993134  331.326508  400.000000  Tree  0.624895  OSBS_029.tif
16  287.350128  139.016800  314.229279  164.446640  Tree  0.603382  OSBS_029.tif
17    0.000000  150.834000   38.386154  205.230545  Tree  0.594185  OSBS_029.tif
18  382.498260  266.036987  400.000000  298.704041  Tree  0.589966  OSBS_029.tif
19    1.984573  222.119019   34.475784  252.937622  Tree  0.577174  OSBS_029.tif
20   46.975739    8.971813   84.499695   50.090435  Tree  0.563153  OSBS_029.tif
21  186.804276  257.105011  228.315018  299.525055  Tree  0.561495  OSBS_029.tif
22  286.566559   85.355003  324.387665  125.718040  Tree  0.551837  OSBS_029.tif
23  234.567520  294.011841  274.479065  334.875793  Tree  0.545394  OSBS_029.tif
24  374.540802  209.400406  398.161835  233.621811  Tree  0.543929  OSBS_029.tif
25   73.763977  257.040527  113.467361  299.843994  Tree  0.541746  OSBS_029.tif
26  192.583923   83.056610  242.978516  135.279297  Tree  0.537536  OSBS_029.tif
27  367.071869  120.614182  387.278351  141.363602  Tree  0.525784  OSBS_029.tif
28  232.225494  243.621368  252.698517  262.646454  Tree  0.520788  OSBS_029.tif
29   77.625854  144.001083  112.081345  177.361404  Tree  0.520145  OSBS_029.tif
30  164.150009  170.871872  199.799088  213.954330  Tree  0.519117  OSBS_029.tif
31  102.766090   38.707230  128.108795   65.090714  Tree  0.516154  OSBS_029.tif
32  311.426147   10.851342  343.345825   41.151402  Tree  0.515354  OSBS_029.tif
33  118.966660   69.120522  146.989456   96.492104  Tree  0.510438  OSBS_029.tif
34  179.346725  374.134094  206.727676  398.573975  Tree  0.500601  OSBS_029.tif
35  313.729645  335.901245  337.536591  359.096558  Tree  0.499219  OSBS_029.tif
36   86.955505  365.541382  107.242508  387.207642  Tree  0.491914  OSBS_029.tif
37   30.507977  141.318390   56.679005  166.302246  Tree  0.480968  OSBS_029.tif
38  370.122314   25.331028  398.215332   55.898685  Tree  0.476110  OSBS_029.tif
39   56.864929  198.027603   87.494843  232.870377  Tree  0.467938  OSBS_029.tif
40  227.109482  389.264709  253.727768  399.880249  Tree  0.465864  OSBS_029.tif
41  142.165863  386.444153  178.620789  399.773315  Tree  0.441629  OSBS_029.tif
42  327.987396  122.410789  357.093964  151.798492  Tree  0.436218  OSBS_029.tif
43    0.000000  258.549438   20.573090  290.715454  Tree  0.431427  OSBS_029.tif
44  235.039627  133.472946  252.705338  149.826157  Tree  0.426352  OSBS_029.tif
45   87.353600    8.077889  114.621773   37.661968  Tree  0.425008  OSBS_029.tif
46    0.583410   56.006218   28.626616  106.935448  Tree  0.408974  OSBS_029.tif
47  100.957260  123.907440  121.769989  145.963257  Tree  0.404019  OSBS_029.tif
```
So if i have an `.jpg` image，How can i predict it ?
