### ISSUE TITLE
Issue in model traning in custom dataset  KeyError: 'tree' 

### ISSUE THREAD

**Issue by sachin22225** [weecology/DeepForest#313]
I am following the colab tutorial and demo to train the model on custom dataset.
I am facing the error in runing 
https://colab.research.google.com/drive/1gKUiocwfCvcvVfiKzAaf6voiUVL2KK_r?usp=sharing

I got this error at this line
```
m.trainer.fit(m)

| Name  | Type      | Params
------------------------------------
0 | model | RetinaNet | 32.1 M
------------------------------------
31.9 M    Trainable params
222 K     Non-trainable params
32.1 M    Total params
128.592   Total estimated model params size (MB)
Validation sanity check: 0%
0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-11-303f7dbf2176>](https://localhost:8080/#) in <module>()
      1 start_time = time.time()
----> 2 m.trainer.fit(m)
      3 print(f"--- Training on CPU: {(time.time() - start_time):.2f} seconds ---")

20 frames
[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    432             # instantiate since we don't know how to
    433             raise RuntimeError(msg) from None
--> 434         raise exception
    435 
    436 

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/deepforest/dataset.py", line 100, in __getitem__
    lambda x: self.label_dict[x]).values.astype(np.int64)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/apply.py", line 1043, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/apply.py", line 1101, in apply_standard
    convert=self.convert_dtype,
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "/usr/local/lib/python3.7/dist-packages/deepforest/dataset.py", line 100, in <lambda>
    lambda x: self.label_dict[x]).values.astype(np.int64)
KeyError: 'tree' 

```
I have created the dataset using labelmg. The dataset look like this
	image_path	xmin	ymin	xmax	ymax	label
0	1.jpg	          570	159	          593	193	        tree
1	1.jpg	           581	221	          609	252	        tree
2	1.jpg	          581	277	          627	311	        tree
3	1.jpg	          597	170	          636	205	        tree
4	1.jpg	          198	413	          354	553	        tree

**Comment by bw4sz** [comment]
Please format your code.

```
code
```

and include a full reproducible example, or atleast the full set of code. I believe you did not chance the label_dict from 'Tree' to 'tree', notice the capital. Just guessing.

**Comment by sachin22225** [comment]
Yes I have converted tree to Tree. It is working now
