### ISSUE TITLE
Error on install from pypi

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#46]
```python
>>> from deepforest import deepforest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ethan/DeepForest/deepforest/deepforest.py", line 10, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by bw4sz** [comment]
can't reproduce locally

```

source test/bin/activate
pip install DeepForest
pip install git+git://github.com/bw4sz/keras-retinanet.git
python
(test) MacBook-Pro:Desktop ben$ python
```

```
...
Successfully built keras-retinanet
Installing collected packages: keras-resnet, cython, python-utils, progressbar2, keras-retinanet
Successfully installed cython-0.29.14 keras-resnet-0.1.0 keras-retinanet-0.5.1 progressbar2-3.47.0 python-utils-2.3.0
(test) MacBook-Pro:Downloads ben$ python
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepforest
>>> deepforest.__version__
'0.2.4'
```
will try on a linux azure machine.

**Comment by bw4sz** [comment]
Cannot reproduce on blank linux azure instance

```
bweinstein@a:~$ pip install DeepForest
Collecting DeepForest
  Downloading https://files.pythonhosted.org/packages/de/e8/4b95d610fda0374c3d4dc59285fb0a9a989af2b8b6bf9ad14e09ef2f92d5/deepforest-0.2.4-py2.py3-none-any.whl (1.0MB)
     |████████████████████████████████| 1.0MB 33.4MB/s
Requirement already satisfied: pyyaml in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (3.13)
Requirement already satisfied: pandas in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (0.25.3)
Collecting tensorflow==1.14
  Downloading https://files.pythonhosted.org/packages/7c/fb/7b2c5b3e85ad335b53ca67deb2ef4af574dc0a8759f43b7f45e15005e449/tensorflow-1.14.0-cp35-cp35m-manylinux1_x86_64.whl (109.2MB)
     |████████████████████████████████| 109.2MB 72kB/s
Requirement already satisfied: tqdm in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (4.37.0)
Collecting slidingwindow
  Downloading https://files.pythonhosted.org/packages/3d/15/a2a2dc82fe9fa9699062b24e84e2cd2620f4ac0e2089d24eb8d0de0ce7ec/slidingwindow-0.0.13-py2.py3-none-any.whl
Requirement already satisfied: pillow in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (5.2.0)
Requirement already satisfied: keras>2.3.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (2.3.1)
Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: matplotlib in /data/anaconda/envs/py35/lib/python3.5/site-packages (from DeepForest) (3.0.0)
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/59/dc/f4a3c35673512e3bfaa48c4e3b6c1bc3e262a8a2bfc9ffef986780d15ad3/opencv_python-4.1.2.30-cp35-cp35m-manylinux1_x86_64.whl (28.3MB)
     |████████████████████████████████| 28.3MB 27.3MB/s
Requirement already satisfied: pytz>=2017.2 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from pandas->DeepForest) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from pandas->DeepForest) (1.17.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from pandas->DeepForest) (2.8.0)
Requirement already satisfied: wheel>=0.26 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (0.31.1)
Requirement already satisfied: gast>=0.2.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (0.2.2)
Requirement already satisfied: six>=1.10.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.11.0)
Requirement already satisfied: google-pasta>=0.1.6 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (0.1.8)
Requirement already satisfied: absl-py>=0.7.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (0.8.1)
Requirement already satisfied: keras-applications>=1.0.6 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.1.0)
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0
  Downloading https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488kB)
     |████████████████████████████████| 491kB 41.9MB/s
Collecting tensorboard<1.15.0,>=1.14.0
  Downloading https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl (3.1MB)
     |████████████████████████████████| 3.2MB 53.5MB/s
Requirement already satisfied: termcolor>=1.1.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.1.0)
Requirement already satisfied: astor>=0.6.0 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (0.8.0)
Requirement already satisfied: grpcio>=1.8.6 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.24.3)
Requirement already satisfied: protobuf>=3.6.1 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (3.10.0)
Requirement already satisfied: wrapt>=1.11.1 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorflow==1.14->DeepForest) (1.11.2)
Requirement already satisfied: psutil in /data/anaconda/envs/py35/lib/python3.5/site-packages (from slidingwindow->DeepForest) (5.4.7)
Requirement already satisfied: h5py in /data/anaconda/envs/py35/lib/python3.5/site-packages (from keras>2.3.0->DeepForest) (2.8.0)
Requirement already satisfied: scipy>=0.14 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from keras>2.3.0->DeepForest) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib->DeepForest) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib->DeepForest) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from matplotlib->DeepForest) (2.4.2)
Requirement already satisfied: werkzeug>=0.11.15 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14->DeepForest) (0.16.0)
Collecting setuptools>=41.0.0
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
     |████████████████████████████████| 583kB 53.5MB/s
Requirement already satisfied: markdown>=2.6.8 in /data/anaconda/envs/py35/lib/python3.5/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14->DeepForest) (3.1.1)
ERROR: onnx-chainer 1.5.0 has requirement onnx<1.6,>=1.4.0, but you'll have onnx 1.6.0 which is incompatible.
ERROR: tensorflow-gpu 2.0.0 has requirement tensorboard<2.1.0,>=2.0.0, but you'll have tensorboard 1.14.0 which is incompatible.
ERROR: tensorflow-gpu 2.0.0 has requirement tensorflow-estimator<2.1.0,>=2.0.0, but you'll have tensorflow-estimator 1.14.0 which is incompatible.
Installing collected packages: tensorflow-estimator, setuptools, tensorboard, tensorflow, slidingwindow, xmltodict, opencv-python, DeepForest
  Found existing installation: tensorflow-estimator 2.0.1
    Uninstalling tensorflow-estimator-2.0.1:
      Successfully uninstalled tensorflow-estimator-2.0.1
  Found existing installation: setuptools 40.2.0
    Uninstalling setuptools-40.2.0:
      Successfully uninstalled setuptools-40.2.0
  Found existing installation: tensorboard 2.0.1
    Uninstalling tensorboard-2.0.1:
      Successfully uninstalled tensorboard-2.0.1
Successfully installed DeepForest-0.2.4 opencv-python-4.1.2.30 setuptools-42.0.2 slidingwindow-0.0.13 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 xmltodict-0.12.0
bweinstein@a:~$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepforest
>>> deepforest.__version__
'0.2.4'
```

**Comment by bw4sz** [comment]
Perhaps conflicting python versions?

https://stackoverflow.com/questions/26505958/why-cant-python-import-image-from-pil

we can try within a virtualenv.

**Comment by ethanwhite** [comment]
Possibly. I'll try to dig into it on that machine when I get a few minutes.

**Comment by ethanwhite** [comment]
I've got it working now. Some weird conda + base Python issue. Sorry for the noise.
