### ISSUE TITLE
Bird detector should update label_dict automatically. 

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#488]
```
from deepforest import main
from deepforest import utilities
import os

# Load annotations made in QGIS and finetune the bird model
rgb_file="/Users/benweinstein/Downloads/2022_03_10_2022ImagingRnD_14_14_42_07336.JPG_ST_4.JPG"
shapefile="/Users/benweinstein/Downloads/2022_03_10_2022ImagingRnD_14_14_42_07336.shp"
annotations = utilities.shapefile_to_annotations(rgb=rgb_file, shapefile=shapefile)
annotation_path = "/Users/benweinstein/Downloads/2022_03_10_2022ImagingRnD_14_14_42_07336.csv"
annotations.to_csv(annotation_path)
m = main.deepforest()
m.use_bird_release()
m.config["train"]["root_dir"] = os.path.dirname(annotation_path)
m.config["train"]["csv_file"] = annotation_path
m.config["train"]["epochs"] = 2
m.create_trainer()
m.trainer.fit(m)

# Run some evaluate, repeat above with seperate annotations
#m.config["eval"]["csv_file"] = <file>
#m.evaluate()

# Save model for later
m.save_model("finetuned_model")
```

```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/benweinstein/Documents/DeepForest/deepforest/dataset.py", line 109, in __getitem__
    targets["labels"] = image_annotations.label.apply(
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/pandas/core/series.py", line 4356, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/pandas/core/apply.py", line 1036, in apply
    return self.apply_standard()
  File "/Users/benweinstein/.conda/envs/DeepForest/lib/python3.9/site-packages/pandas/core/apply.py", line 1092, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "/Users/benweinstein/Documents/DeepForest/deepforest/dataset.py", line 110, in <lambda>
    lambda x: self.label_dict[x]).values.astype(np.int64)
KeyError: 'Bird'
```

When you use_bird_release, it should update label_dict.

**Comment by bw4sz** [comment]
I checked out a branch and created a new test to assert this error.

```
   def test_use_bird_release(m):
        imgpath = get_data("AWPE Pigeon Lake 2020 DJI_0005.JPG")
        m.use_bird_release()
        boxes = m.predict_image(path=imgpath)
        assert not boxes.empty
>       assert boxes.label.unique() == "Bird"
E       AssertionError: assert array(['Tree'], dtype=object) == 'Bird'
```
