### ISSUE TITLE
Warn users about new config args

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#582]
As we add config args, but users might have old configs, we should tell them that they are missing keys and link to the 

https://deepforest.readthedocs.io/en/latest/ConfigurationFile.html

```
os.getcwd()
'/home/b.weinstein/EvergladesTools'
        m = main.deepforest(num_classes=classes, label_dict=label_dict, config_file="Airplane/deepforest_config.yml")
Reading config file: Airplane/deepforest_config.yml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/orange/ewhite/b.weinstein/miniconda3/envs/EvergladesTools/lib/python3.11/site-packages/deepforest/main.py", line 64, in __init__
    self.create_model()
  File "/orange/ewhite/b.weinstein/miniconda3/envs/EvergladesTools/lib/python3.11/site-packages/deepforest/main.py", line 162, in create_model
    self.config["architecture"]))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'architecture'
```

https://github.com/weecology/DeepForest/blob/04a108483160242e2c68a57673864e0344f03f8e/deepforest/main.py#L57C23-L57C32

**Comment by Om-Doiphode** [comment]
Can I work on this issue?

**Comment by henrykironde** [comment]
This is old and covered
