### ISSUE TITLE
Import error when running deepforest from the repository directory

### ISSUE THREAD

**Issue by ethanwhite** [weecology/DeepForest#85]
When running in all other directories DeepForest works as expected:

```python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Using TensorFlow backend.
```

But when running inside the repository directory (something that's fairly common during development) it errors:

```python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ethan/Dropbox/Informatics/DeepForest/deepforest/deepforest.py", line 27, in <module>
    from deepforest.retinanet_train import main as retinanet_train
  File "/home/ethan/Dropbox/Informatics/DeepForest/deepforest/retinanet_train.py", line 18, in <module>
    from keras_retinanet import layers 
  File "/home/ethan/Dropbox/Informatics/DeepForest/keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "/home/ethan/Dropbox/Informatics/DeepForest/keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "/home/ethan/Dropbox/Informatics/DeepForest/keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'
```

Likely has something to do with the embedded `keras_retinanet` fork directory.

**Comment by bw4sz** [comment]
I'll make it clearer on the front of the repo. Keras retinanet has a c++ cython dependency that is built on pip install, you need to run

```
setup.py build_ext --inplace
``

add to README

**Comment by bw4sz** [comment]
nevermind, it was already there.

https://github.com/weecology/DeepForest#source-installation
